### ISSUE TITLE
Prueba 1

### ISSUE THREAD

**Issue by nbxandresvejar** [Arcont01/Ejercicio-Tecnica-de-Encriptacion#3]
- Existen reglas y validaciones que no están cubiertas
- Se recomienda el uso de clases y tratamiento de errores
- Puedes usar cualquier framework (o estilo) que consideres
- Hacer uso de pruebas unitarias

**Comment by Arcont01** [comment]
Hola tengo varias dudas y puntos que pues nunca me aclararon.   

1. Cuanto tiempo tengo para corregir errores.
2. Al usar un framework es posible entonces cambiar todo lo ya hecho?.

**Comment by Arcont01** [comment]
Se implementa lumen con clases y pruebas unitarias y se agregan mas condiciones
