### ISSUE TITLE
Prueba 2

### ISSUE THREAD

**Issue by nbxandresvejar** [Arcont01/Ejercicio-Tecnica-de-Encriptacion#4]
- Existen reglas y validaciones que no están cubiertas
- Se recomienda tratamiento de errores

**Comment by Arcont01** [comment]
Se estan tratando posibles errores

**Comment by Arcont01** [comment]
Se crea un log donde se guardan posibles errores así como errores inesperados y se crea una excepcion custom, así también se hacen cambios en la verificación de posibles casos que no deberían pasar
